---
format_version: '13'
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
project_type: other

include:
- path: included.yml

pipelines:
  release:
    workflows:
      build: {} # defined here (local)
      deploy: {} # defined in included.yml → GHOST + jump
      new: {}
step_bundles:
  common:
    steps:
    - script@1:
        title: 'test'
workflows:
  build:
    before_run:
    - setup #                defined in included.yml → GHOST + jump. test
    steps:
    - bundle::common:
        title: common new
        # local step bundle
    - bundle::shared: {} # defined in included.yml → GHOST + jump
  test:
    steps:
    - script@1: {}
meta:
  bitrise.io:
    stack: linux-docker-android-22.04
    machine_type_id: standard
