---
format_version: '13'
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
project_type: other

include:
- path: included.yml
- path: test.yml
- path: here/is/a/very/long/path/test/so/someone/help/please.yml

pipelines:
  release:
    workflows:
      build: {} # defined here (local)
      deploy: {} # defined in included.yml → GHOST + jump
      new: {}
step_bundles:
  common:
    steps:
    - script@1:
        title: 'harmadik'
workflows:
  new:
    envs:
    - ggg: gggg
      opts:
        is_expand: false
  build:
    before_run:
    - setup #                defined in included.yml → GHOST + jump. test
    steps:
    - bundle::common:
        title: common new
        # local step bundle
    - bundle::shared:
        title: title
        # defined in included.yml → GHOST + jump
  test:
    steps:
    - script@1: {}
meta:
  bitrise.io:
    stack: linux-docker-android-22.04
    machine_type_id: standard
app:
  envs:
  - okok: "nono"
    opts:
      is_expand: false
